### ISSUE TITLE
TODO: The final countdown

### ISSUE THREAD

**Issue by Mr-357** [Etheraex/SBP#5]
- [x] dodati svima bool u konstruktor DTO-a da ne ulazimo u stackoverflow (ostalo alijansaispunjava,igracispunjava,lik,sesija,rasa mozda jos nesto , proveriti sve, igrac DTO ima primer kako se koristi)

- [x] popraviti createorupdate fju (naci nacin da ne ulazi u stackoverflow)

- [x] proveriti rad kontrolera, trebalo bi da vecina GET rade trenutno (pogotovo kad dodamo svima konstruktor)

- [x] izbaciti jquery/bootstrap?

createorupdate mora da se popravi da bi radilo save i/ili update jer smo tako DTOManager napravili

winforma je pokvarena tako da ne pokusavajte da je pokrecete

ima neke greskice i kod kontrolera, npr za predmet i za rasu mora da se resi ono sto mora specificno da se loaduje (mozda bolje poseban kontroler za svaku rasu i svaki tip predmeta?)

**Comment by Mr-357** [comment]
naravno ako znate pametniji nacin da ovo resimo a da nije hardkodovanje set null na svemu, slobodno predlozite

ako bas zapnemo onda idemo hardcode set null na sve pa sta bude

**Comment by Mr-357** [comment]
ostalo testiranje svega, ako vas ne mrzi mozete da testirate i winform aplikaciju, builduje se ali mgouce je da nece bas sve da radi kako treba, toliko od mene

**Comment by Mr-357** [comment]
is done
